version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: bank-postgres
    restart: always
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: UTC
      PGTZ: UTC
    ports:
      - "5432:5432"
    command: >
      postgres
      -c timezone=UTC
      -c log_timezone=UTC
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
